config/routes.rb
RominaBlog::Application.routes.draw do
  root 'posts#index'
  easy_auth_routes

  get '/destroyed' => 'posts#destroyed'
  page :about

  resources :posts do
    put 'restore'
    resources :comments
  end
  get  '/sign_up' => 'users#new'
  post '/sign_up' => 'users#create'
end

app/models/admin_user.rb
class AdminUser < User
  has_many :posts, dependent: :destroy
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  include ContextValidations::Model
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
  include ContextValidations::Model
  include DestroyedAt
  belongs_to :admin_user
  has_many :comments, dependent: :destroy

  def self.destroyed
    unscoped.where('destroyed_at IS NOT NULL')
  end
end

app/models/reader_user.rb
class ReaderUser < User

end

app/models/user.rb
class User < ActiveRecord::Base
  include EasyAuth::Models::Account
  include ContextValidations::Model
  has_many :comments, dependent: :destroy

  def can_admin?(resource)
    resource.admin_user_id == self.id
  end

  def is_admin?
    AdminUser === self
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include EasyAuthHelper
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  include ContextValidations::Controller

  def create
    @post = Post.find(params[:post_id])
    @comment = Comment.new(comment_params)
    @comment.post = @post
    @comment.validations = validations

    if @comment.save
      redirect_to post_path(params[:post_id])
    else
      render 'posts/show'
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end

  def base_validations
    validates :content, presence: true
  end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include ContextValidations::Controller

  def index
    @posts = Post.all.order('id DESC')
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
  end

  def new
    @post = current_user.posts.new
  end

  def create
    @post = current_user.posts.new(post_params)
    @post.validations = validations

    if @post.save
      redirect_to posts_path
    else
      render 'new'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.validations = validations

    if @post.update_attributes(post_params)
      redirect_to posts_path
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  def destroyed
    @posts = Post.destroyed
  end

  def restore
    @post = Post.unscoped.find(params[:post_id])
    @post.restore
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :content)
  end

  def base_validations
    validates :title, presence: true, uniqueness: { conditions: -> { where(destroyed_at: nil) } }
    validates :content, presence: true
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include EasyAuth::Controllers::Sessions

  def after_successful_sign_in_url_default
    root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include ContextValidations::Controller

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.validations = validations

    if @user.save
      @user.password_identities.reload
      session[:identity_id] = @user.password_identities.first.id
      redirect_to root_path
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :type)
  end

  def base_validations
    validates :email, presence: true, uniqueness: true
  end

  def create_validations
    validates :password, presence: true, confirmation: true
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_comment.html.haml
.comment
  %h5= comment.content
  %p.time-stamp submitted #{time_ago_in_words(comment.created_at)} ago
  %hr

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title Romina's Blog
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag 'application', :media => "all"
    = javascript_include_tag "application"
    %link(href="images/favicon.ico" rel="shortcut icon")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114")

  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
            %a.brand{:href => root_path} Romina's Blog
          .container.nav-collapse
            %ul.nav
              %li= link_to 'About', about_path
              - if current_user
                %li= link_to 'Sign out', sign_out_path
              - else
                %li= link_to 'Sign up', sign_up_path
                %li= link_to 'Sign in', sign_in_path


    .container
      .content
        .row
          .span12
            = yield

      %footer

app/views/pages/about.html.haml
.page-header
  %h1 What is this app, you say?

%p A blog app. Whether you're an administrator or a regular user, you can make use of several of this site's features.
%strong Admins:
%ul
  %li Want to post a blog? No problem
  %li Realized you made a spelling mistake and need to update your blog? No problem
  %li Failed at blogging and want to delete ASAP? No problem
  %li Changed your mind and want to restore your previously deleted post? No problem
  %li Have something to say about your own or someone else's post? No problem
  %li Just want to lurk and see all posts? No problem

%strong Other registered users:
%p Even though your actions may be more limited than the aforementioned, you may still view all the posts and comment on them. How fun!

%h3 Thanks for visiting! :)

app/views/posts/destroyed.html.haml
.page-header
  %h1 Deleted Posts

- @posts.each do |post|
  .blog-post
    .blog-title
      = post.title
      - if current_user.can_admin?(post)
        %p= link_to 'Restore', post_restore_path(post), method: :put
    %hr

app/views/posts/edit.html.haml
.page-header
  %h1 Edit Post

= simple_form_for @post do |f|
  = f.input :title
  = f.input :content

  = f.submit 'Submit', class: 'btn'

app/views/posts/index.html.haml
.page-header
  %h1 Posts

- if current_user
  - if current_user.is_admin?
    = link_to 'New post', new_post_path, class: 'btn'
    = link_to 'Deleted posts', destroyed_path, class: 'btn'

- @posts.each do |post|
  .blog-post
    .blog-title= link_to post.title, post
    %hr

app/views/posts/new.html.haml
.page-header
  %h1 New Post

= simple_form_for @post do |f|
  = f.input :title
  = f.input :content

  = f.submit 'Submit', class: 'btn'

app/views/posts/show.html.haml
.page-header
  %h1= @post.title

- if current_user
  - if current_user.can_admin?(@post)
    = link_to 'Edit', [:edit, @post], class: 'btn'
    = link_to 'Delete', @post, method: :delete, data: {confirm: 'Are you sure you want to delete this post?'}, class: 'btn'

.blog-content= @post.content

- if current_user
  %h3 Comment:
  = simple_form_for [@post, @comment] do |f|
    %p= f.input :content, as: :text

    %p= f.submit 'Submit', class: 'btn'

= render @post.comments

app/views/posts/show_destroyed.html.haml
.page-header
  %h1 Deleted Posts

- @posts.each do |post|
  .blog-post
    .blog-title
      = post.title
      - if current_user.can_admin?(post)
        %p= link_to 'Restore', post_restore_path(post), method: :put
    %hr

app/views/users/new.html.haml
.page-header
  %h1 Sign Up

= simple_form_for @user, url: sign_up_path do |f|
  = f.input :email
  = f.input :password
  = f.input :password_confirmation
  = f.select :type, ['AdminUser', 'ReaderUser']

  = f.submit 'Sign up', class: 'btn'